/* Generated By:JJTree&JavaCC: Do not edit this line. YouTrackDBSqlConstants.java */
package com.jetbrains.youtrackdb.internal.core.sql.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface YouTrackDBSqlConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int FORMAL_COMMENT = 8;
  /** RegularExpression Id. */
  int MULTI_LINE_COMMENT = 9;
  /** RegularExpression Id. */
  int SELECT = 11;
  /** RegularExpression Id. */
  int MATCH = 12;
  /** RegularExpression Id. */
  int INSERT = 13;
  /** RegularExpression Id. */
  int CREATE = 14;
  /** RegularExpression Id. */
  int DELETE = 15;
  /** RegularExpression Id. */
  int CASCADE = 16;
  /** RegularExpression Id. */
  int VERTEX = 17;
  /** RegularExpression Id. */
  int EDGE = 18;
  /** RegularExpression Id. */
  int UPDATE = 19;
  /** RegularExpression Id. */
  int UPSERT = 20;
  /** RegularExpression Id. */
  int FROM = 21;
  /** RegularExpression Id. */
  int TO = 22;
  /** RegularExpression Id. */
  int WHERE = 23;
  /** RegularExpression Id. */
  int WHILE = 24;
  /** RegularExpression Id. */
  int INTO = 25;
  /** RegularExpression Id. */
  int VALUE = 26;
  /** RegularExpression Id. */
  int VALUES = 27;
  /** RegularExpression Id. */
  int SET = 28;
  /** RegularExpression Id. */
  int ADD = 29;
  /** RegularExpression Id. */
  int PUT = 30;
  /** RegularExpression Id. */
  int MERGE = 31;
  /** RegularExpression Id. */
  int CONTENT = 32;
  /** RegularExpression Id. */
  int REMOVE = 33;
  /** RegularExpression Id. */
  int INCREMENT = 34;
  /** RegularExpression Id. */
  int AND = 35;
  /** RegularExpression Id. */
  int OR = 36;
  /** RegularExpression Id. */
  int NULL = 37;
  /** RegularExpression Id. */
  int DEFINED = 38;
  /** RegularExpression Id. */
  int ORDER = 39;
  /** RegularExpression Id. */
  int GROUP = 40;
  /** RegularExpression Id. */
  int BY = 41;
  /** RegularExpression Id. */
  int LIMIT = 42;
  /** RegularExpression Id. */
  int SKIP2 = 43;
  /** RegularExpression Id. */
  int BATCH = 44;
  /** RegularExpression Id. */
  int OFFSET = 45;
  /** RegularExpression Id. */
  int TIMEOUT = 46;
  /** RegularExpression Id. */
  int ASC = 47;
  /** RegularExpression Id. */
  int AS = 48;
  /** RegularExpression Id. */
  int DESC = 49;
  /** RegularExpression Id. */
  int FETCHPLAN = 50;
  /** RegularExpression Id. */
  int RETURN = 51;
  /** RegularExpression Id. */
  int BEFORE = 52;
  /** RegularExpression Id. */
  int AFTER = 53;
  /** RegularExpression Id. */
  int RECORD = 54;
  /** RegularExpression Id. */
  int WAIT = 55;
  /** RegularExpression Id. */
  int RETRY = 56;
  /** RegularExpression Id. */
  int LET = 57;
  /** RegularExpression Id. */
  int CACHE = 58;
  /** RegularExpression Id. */
  int CYCLE = 59;
  /** RegularExpression Id. */
  int NOCACHE = 60;
  /** RegularExpression Id. */
  int NOLIMIT = 61;
  /** RegularExpression Id. */
  int NOCYCLE = 62;
  /** RegularExpression Id. */
  int UNSAFE = 63;
  /** RegularExpression Id. */
  int PARALLEL = 64;
  /** RegularExpression Id. */
  int STRATEGY = 65;
  /** RegularExpression Id. */
  int DEPTH_FIRST = 66;
  /** RegularExpression Id. */
  int BREADTH_FIRST = 67;
  /** RegularExpression Id. */
  int LUCENE = 68;
  /** RegularExpression Id. */
  int NEAR = 69;
  /** RegularExpression Id. */
  int WITHIN = 70;
  /** RegularExpression Id. */
  int UNWIND = 71;
  /** RegularExpression Id. */
  int MAXDEPTH = 72;
  /** RegularExpression Id. */
  int MINDEPTH = 73;
  /** RegularExpression Id. */
  int CLASS = 74;
  /** RegularExpression Id. */
  int SUPERCLASS = 75;
  /** RegularExpression Id. */
  int CLASSES = 76;
  /** RegularExpression Id. */
  int SUPERCLASSES = 77;
  /** RegularExpression Id. */
  int UPDATABLE = 78;
  /** RegularExpression Id. */
  int EXCEPTION = 79;
  /** RegularExpression Id. */
  int PROFILE = 80;
  /** RegularExpression Id. */
  int STORAGE = 81;
  /** RegularExpression Id. */
  int ON = 82;
  /** RegularExpression Id. */
  int OFF = 83;
  /** RegularExpression Id. */
  int TRUNCATE = 84;
  /** RegularExpression Id. */
  int POLYMORPHIC = 85;
  /** RegularExpression Id. */
  int EXTENDS = 86;
  /** RegularExpression Id. */
  int ABSTRACT = 87;
  /** RegularExpression Id. */
  int ALTER = 88;
  /** RegularExpression Id. */
  int NAME = 89;
  /** RegularExpression Id. */
  int STRICT_MODE = 90;
  /** RegularExpression Id. */
  int CUSTOM = 91;
  /** RegularExpression Id. */
  int DESCRIPTION = 92;
  /** RegularExpression Id. */
  int DROP = 93;
  /** RegularExpression Id. */
  int PROPERTY = 94;
  /** RegularExpression Id. */
  int FORCE = 95;
  /** RegularExpression Id. */
  int METADATA = 96;
  /** RegularExpression Id. */
  int INDEX = 97;
  /** RegularExpression Id. */
  int COLLATE = 98;
  /** RegularExpression Id. */
  int ENGINE = 99;
  /** RegularExpression Id. */
  int REBUILD = 100;
  /** RegularExpression Id. */
  int ID = 101;
  /** RegularExpression Id. */
  int DATABASE = 102;
  /** RegularExpression Id. */
  int OPTIMIZE = 103;
  /** RegularExpression Id. */
  int LINK = 104;
  /** RegularExpression Id. */
  int TYPE = 105;
  /** RegularExpression Id. */
  int INVERSE = 106;
  /** RegularExpression Id. */
  int EXPLAIN = 107;
  /** RegularExpression Id. */
  int GRANT = 108;
  /** RegularExpression Id. */
  int REVOKE = 109;
  /** RegularExpression Id. */
  int READ = 110;
  /** RegularExpression Id. */
  int EXECUTE = 111;
  /** RegularExpression Id. */
  int ALL = 112;
  /** RegularExpression Id. */
  int NONE = 113;
  /** RegularExpression Id. */
  int FUNCTION = 114;
  /** RegularExpression Id. */
  int PARAMETERS = 115;
  /** RegularExpression Id. */
  int IDEMPOTENT = 116;
  /** RegularExpression Id. */
  int LANGUAGE = 117;
  /** RegularExpression Id. */
  int BEGIN = 118;
  /** RegularExpression Id. */
  int COMMIT = 119;
  /** RegularExpression Id. */
  int ROLLBACK = 120;
  /** RegularExpression Id. */
  int IF = 121;
  /** RegularExpression Id. */
  int ELSE = 122;
  /** RegularExpression Id. */
  int CONTINUE = 123;
  /** RegularExpression Id. */
  int FAIL = 124;
  /** RegularExpression Id. */
  int SLEEP = 125;
  /** RegularExpression Id. */
  int CONSOLE = 126;
  /** RegularExpression Id. */
  int BLOB = 127;
  /** RegularExpression Id. */
  int SHARED = 128;
  /** RegularExpression Id. */
  int DEFAULT_ = 129;
  /** RegularExpression Id. */
  int SEQUENCE = 130;
  /** RegularExpression Id. */
  int START = 131;
  /** RegularExpression Id. */
  int OPTIONAL = 132;
  /** RegularExpression Id. */
  int COUNT = 133;
  /** RegularExpression Id. */
  int DISTINCT = 134;
  /** RegularExpression Id. */
  int HA = 135;
  /** RegularExpression Id. */
  int STATUS = 136;
  /** RegularExpression Id. */
  int SERVER = 137;
  /** RegularExpression Id. */
  int SYNC = 138;
  /** RegularExpression Id. */
  int EXISTS = 139;
  /** RegularExpression Id. */
  int FOREACH = 140;
  /** RegularExpression Id. */
  int DEPTH_ALIAS = 141;
  /** RegularExpression Id. */
  int PATH_ALIAS = 142;
  /** RegularExpression Id. */
  int IDENTIFIED = 143;
  /** RegularExpression Id. */
  int ROLE = 144;
  /** RegularExpression Id. */
  int USER = 145;
  /** RegularExpression Id. */
  int USERS = 146;
  /** RegularExpression Id. */
  int RID = 147;
  /** RegularExpression Id. */
  int SECURITY = 148;
  /** RegularExpression Id. */
  int POLICY = 149;
  /** RegularExpression Id. */
  int SYSTEM = 150;
  /** RegularExpression Id. */
  int THIS = 151;
  /** RegularExpression Id. */
  int RECORD_ATTRIBUTE = 152;
  /** RegularExpression Id. */
  int RID_ATTR = 153;
  /** RegularExpression Id. */
  int RID_STRING = 154;
  /** RegularExpression Id. */
  int CLASS_ATTR = 155;
  /** RegularExpression Id. */
  int VERSION_ATTR = 156;
  /** RegularExpression Id. */
  int SIZE_ATTR = 157;
  /** RegularExpression Id. */
  int TYPE_ATTR = 158;
  /** RegularExpression Id. */
  int RAW_ATTR = 159;
  /** RegularExpression Id. */
  int RID_ID_ATTR = 160;
  /** RegularExpression Id. */
  int RID_POS_ATTR = 161;
  /** RegularExpression Id. */
  int FIELDS_ATTR = 162;
  /** RegularExpression Id. */
  int INTEGER_LITERAL = 163;
  /** RegularExpression Id. */
  int DECIMAL_LITERAL = 164;
  /** RegularExpression Id. */
  int HEX_LITERAL = 165;
  /** RegularExpression Id. */
  int OCTAL_LITERAL = 166;
  /** RegularExpression Id. */
  int FLOATING_POINT_LITERAL = 167;
  /** RegularExpression Id. */
  int DECIMAL_FLOATING_POINT_LITERAL = 168;
  /** RegularExpression Id. */
  int DECIMAL_EXPONENT = 169;
  /** RegularExpression Id. */
  int HEXADECIMAL_FLOATING_POINT_LITERAL = 170;
  /** RegularExpression Id. */
  int HEXADECIMAL_EXPONENT = 171;
  /** RegularExpression Id. */
  int CHARACTER_LITERAL = 172;
  /** RegularExpression Id. */
  int STRING_LITERAL = 173;
  /** RegularExpression Id. */
  int INTEGER_RANGE = 174;
  /** RegularExpression Id. */
  int ELLIPSIS_INTEGER_RANGE = 175;
  /** RegularExpression Id. */
  int TRUE = 176;
  /** RegularExpression Id. */
  int FALSE = 177;
  /** RegularExpression Id. */
  int LPAREN = 178;
  /** RegularExpression Id. */
  int RPAREN = 179;
  /** RegularExpression Id. */
  int LBRACE = 180;
  /** RegularExpression Id. */
  int RBRACE = 181;
  /** RegularExpression Id. */
  int LBRACKET = 182;
  /** RegularExpression Id. */
  int RBRACKET = 183;
  /** RegularExpression Id. */
  int SEMICOLON = 184;
  /** RegularExpression Id. */
  int COMMA = 185;
  /** RegularExpression Id. */
  int DOT = 186;
  /** RegularExpression Id. */
  int AT = 187;
  /** RegularExpression Id. */
  int DOLLAR = 188;
  /** RegularExpression Id. */
  int BACKTICK = 189;
  /** RegularExpression Id. */
  int EQ = 190;
  /** RegularExpression Id. */
  int EQEQ = 191;
  /** RegularExpression Id. */
  int LT = 192;
  /** RegularExpression Id. */
  int GT = 193;
  /** RegularExpression Id. */
  int BANG = 194;
  /** RegularExpression Id. */
  int TILDE = 195;
  /** RegularExpression Id. */
  int HOOK = 196;
  /** RegularExpression Id. */
  int COLON = 197;
  /** RegularExpression Id. */
  int LE = 198;
  /** RegularExpression Id. */
  int GE = 199;
  /** RegularExpression Id. */
  int NE = 200;
  /** RegularExpression Id. */
  int NEQ = 201;
  /** RegularExpression Id. */
  int SC_OR = 202;
  /** RegularExpression Id. */
  int SC_AND = 203;
  /** RegularExpression Id. */
  int INCR = 204;
  /** RegularExpression Id. */
  int DECR = 205;
  /** RegularExpression Id. */
  int PLUS = 206;
  /** RegularExpression Id. */
  int MINUS = 207;
  /** RegularExpression Id. */
  int STAR = 208;
  /** RegularExpression Id. */
  int SLASH = 209;
  /** RegularExpression Id. */
  int BIT_AND = 210;
  /** RegularExpression Id. */
  int NULL_COALESCING = 211;
  /** RegularExpression Id. */
  int BIT_OR = 212;
  /** RegularExpression Id. */
  int XOR = 213;
  /** RegularExpression Id. */
  int REM = 214;
  /** RegularExpression Id. */
  int LSHIFT = 215;
  /** RegularExpression Id. */
  int PLUSASSIGN = 216;
  /** RegularExpression Id. */
  int MINUSASSIGN = 217;
  /** RegularExpression Id. */
  int STARASSIGN = 218;
  /** RegularExpression Id. */
  int SLASHASSIGN = 219;
  /** RegularExpression Id. */
  int ANDASSIGN = 220;
  /** RegularExpression Id. */
  int ORASSIGN = 221;
  /** RegularExpression Id. */
  int XORASSIGN = 222;
  /** RegularExpression Id. */
  int REMASSIGN = 223;
  /** RegularExpression Id. */
  int LSHIFTASSIGN = 224;
  /** RegularExpression Id. */
  int RSIGNEDSHIFTASSIGN = 225;
  /** RegularExpression Id. */
  int RUNSIGNEDSHIFTASSIGN = 226;
  /** RegularExpression Id. */
  int RSHIFT = 227;
  /** RegularExpression Id. */
  int RUNSIGNEDSHIFT = 228;
  /** RegularExpression Id. */
  int ELLIPSIS = 229;
  /** RegularExpression Id. */
  int RANGE = 230;
  /** RegularExpression Id. */
  int NOT = 231;
  /** RegularExpression Id. */
  int IN = 232;
  /** RegularExpression Id. */
  int LIKE = 233;
  /** RegularExpression Id. */
  int IS = 234;
  /** RegularExpression Id. */
  int BETWEEN = 235;
  /** RegularExpression Id. */
  int CONTAINS = 236;
  /** RegularExpression Id. */
  int CONTAINSALL = 237;
  /** RegularExpression Id. */
  int CONTAINSANY = 238;
  /** RegularExpression Id. */
  int CONTAINSKEY = 239;
  /** RegularExpression Id. */
  int CONTAINSVALUE = 240;
  /** RegularExpression Id. */
  int CONTAINSTEXT = 241;
  /** RegularExpression Id. */
  int MATCHES = 242;
  /** RegularExpression Id. */
  int KEY = 243;
  /** RegularExpression Id. */
  int INSTANCEOF = 244;
  /** RegularExpression Id. */
  int IDENTIFIER = 245;
  /** RegularExpression Id. */
  int QUOTED_IDENTIFIER = 246;
  /** RegularExpression Id. */
  int METADATA_IDENTIFIER = 247;
  /** RegularExpression Id. */
  int LETTER = 248;
  /** RegularExpression Id. */
  int PART_LETTER = 249;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int IN_FORMAL_COMMENT = 1;
  /** Lexical state. */
  int IN_MULTI_LINE_COMMENT = 2;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "<token of kind 6>",
    "\"/*\"",
    "\"*/\"",
    "\"*/\"",
    "<token of kind 10>",
    "<SELECT>",
    "<MATCH>",
    "<INSERT>",
    "<CREATE>",
    "<DELETE>",
    "<CASCADE>",
    "<VERTEX>",
    "<EDGE>",
    "<UPDATE>",
    "<UPSERT>",
    "<FROM>",
    "<TO>",
    "<WHERE>",
    "<WHILE>",
    "<INTO>",
    "<VALUE>",
    "<VALUES>",
    "<SET>",
    "<ADD>",
    "<PUT>",
    "<MERGE>",
    "<CONTENT>",
    "<REMOVE>",
    "<INCREMENT>",
    "<AND>",
    "<OR>",
    "<NULL>",
    "<DEFINED>",
    "<ORDER>",
    "<GROUP>",
    "<BY>",
    "<LIMIT>",
    "<SKIP2>",
    "<BATCH>",
    "<OFFSET>",
    "<TIMEOUT>",
    "<ASC>",
    "<AS>",
    "<DESC>",
    "<FETCHPLAN>",
    "<RETURN>",
    "<BEFORE>",
    "<AFTER>",
    "<RECORD>",
    "<WAIT>",
    "<RETRY>",
    "<LET>",
    "<CACHE>",
    "<CYCLE>",
    "<NOCACHE>",
    "<NOLIMIT>",
    "<NOCYCLE>",
    "<UNSAFE>",
    "<PARALLEL>",
    "<STRATEGY>",
    "<DEPTH_FIRST>",
    "<BREADTH_FIRST>",
    "<LUCENE>",
    "<NEAR>",
    "<WITHIN>",
    "<UNWIND>",
    "<MAXDEPTH>",
    "<MINDEPTH>",
    "<CLASS>",
    "<SUPERCLASS>",
    "<CLASSES>",
    "<SUPERCLASSES>",
    "<UPDATABLE>",
    "<EXCEPTION>",
    "<PROFILE>",
    "<STORAGE>",
    "<ON>",
    "<OFF>",
    "<TRUNCATE>",
    "<POLYMORPHIC>",
    "<EXTENDS>",
    "<ABSTRACT>",
    "<ALTER>",
    "<NAME>",
    "<STRICT_MODE>",
    "<CUSTOM>",
    "<DESCRIPTION>",
    "<DROP>",
    "<PROPERTY>",
    "<FORCE>",
    "<METADATA>",
    "<INDEX>",
    "<COLLATE>",
    "<ENGINE>",
    "<REBUILD>",
    "<ID>",
    "<DATABASE>",
    "<OPTIMIZE>",
    "<LINK>",
    "<TYPE>",
    "<INVERSE>",
    "<EXPLAIN>",
    "<GRANT>",
    "<REVOKE>",
    "<READ>",
    "<EXECUTE>",
    "<ALL>",
    "<NONE>",
    "<FUNCTION>",
    "<PARAMETERS>",
    "<IDEMPOTENT>",
    "<LANGUAGE>",
    "<BEGIN>",
    "<COMMIT>",
    "<ROLLBACK>",
    "<IF>",
    "<ELSE>",
    "<CONTINUE>",
    "<FAIL>",
    "<SLEEP>",
    "<CONSOLE>",
    "<BLOB>",
    "<SHARED>",
    "<DEFAULT_>",
    "<SEQUENCE>",
    "<START>",
    "<OPTIONAL>",
    "<COUNT>",
    "<DISTINCT>",
    "<HA>",
    "<STATUS>",
    "<SERVER>",
    "<SYNC>",
    "<EXISTS>",
    "<FOREACH>",
    "<DEPTH_ALIAS>",
    "<PATH_ALIAS>",
    "<IDENTIFIED>",
    "<ROLE>",
    "<USER>",
    "<USERS>",
    "<RID>",
    "<SECURITY>",
    "<POLICY>",
    "<SYSTEM>",
    "<THIS>",
    "<RECORD_ATTRIBUTE>",
    "<RID_ATTR>",
    "<RID_STRING>",
    "<CLASS_ATTR>",
    "<VERSION_ATTR>",
    "<SIZE_ATTR>",
    "<TYPE_ATTR>",
    "<RAW_ATTR>",
    "<RID_ID_ATTR>",
    "<RID_POS_ATTR>",
    "<FIELDS_ATTR>",
    "<INTEGER_LITERAL>",
    "<DECIMAL_LITERAL>",
    "<HEX_LITERAL>",
    "<OCTAL_LITERAL>",
    "<FLOATING_POINT_LITERAL>",
    "<DECIMAL_FLOATING_POINT_LITERAL>",
    "<DECIMAL_EXPONENT>",
    "<HEXADECIMAL_FLOATING_POINT_LITERAL>",
    "<HEXADECIMAL_EXPONENT>",
    "<CHARACTER_LITERAL>",
    "<STRING_LITERAL>",
    "<INTEGER_RANGE>",
    "<ELLIPSIS_INTEGER_RANGE>",
    "<TRUE>",
    "<FALSE>",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\";\"",
    "\",\"",
    "\".\"",
    "\"@\"",
    "\"$\"",
    "\"`\"",
    "\"=\"",
    "\"==\"",
    "\"<\"",
    "\">\"",
    "\"!\"",
    "\"~\"",
    "\"?\"",
    "\":\"",
    "\"<=\"",
    "\">=\"",
    "\"!=\"",
    "\"<>\"",
    "\"||\"",
    "\"&&\"",
    "\"++\"",
    "\"--\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"&\"",
    "\"??\"",
    "\"|\"",
    "\"^\"",
    "\"%\"",
    "\"<<\"",
    "\"+=\"",
    "\"-=\"",
    "\"*=\"",
    "\"/=\"",
    "\"&=\"",
    "\"|=\"",
    "\"^=\"",
    "\"%=\"",
    "\"<<=\"",
    "\">>=\"",
    "\">>>=\"",
    "\">>\"",
    "\">>>\"",
    "\"...\"",
    "\"..\"",
    "<NOT>",
    "<IN>",
    "<LIKE>",
    "<IS>",
    "<BETWEEN>",
    "<CONTAINS>",
    "<CONTAINSALL>",
    "<CONTAINSANY>",
    "<CONTAINSKEY>",
    "<CONTAINSVALUE>",
    "<CONTAINSTEXT>",
    "<MATCHES>",
    "<KEY>",
    "<INSTANCEOF>",
    "<IDENTIFIER>",
    "<QUOTED_IDENTIFIER>",
    "<METADATA_IDENTIFIER>",
    "<LETTER>",
    "<PART_LETTER>",
    "\"#\"",
    "\"__@recordmap@___\"",
  };

}
